
package org.usfirst.frc.team157.robot;

// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static ScaledCANJaguar driveLeftJag1;
	public static ScaledCANJaguar driveLeftJag2;
	public static ScaledCANJaguar driveRightJag1;
	public static ScaledCANJaguar driveRightJag2;
	
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	public static void init()
	{
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		driveLeftJag1 = new ScaledCANJaguar(2);
		driveLeftJag2 = new ScaledCANJaguar(4);
		driveRightJag1 = new ScaledCANJaguar(6);
		driveRightJag2 = new ScaledCANJaguar(7);
		
		driveLeftJag1.setScalingFactor(1);
		driveLeftJag2.setScalingFactor(1);
		driveRightJag1.setScalingFactor(1);
		driveRightJag2.setScalingFactor(1);
		
		Robot.setupJagForVoltageControl(driveLeftJag1);
		Robot.setupJagForVoltageControl(driveLeftJag2);
		Robot.setupJagForVoltageControl(driveRightJag1);
		Robot.setupJagForVoltageControl(driveRightJag2);
	}
}
