// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc157.BuiltRobot;
    
import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANJaguar simpleMotorCimJag;
    public static CANJaguar driveDriveFL;
    public static CANJaguar driveDriveFR;
    public static CANJaguar driveDriveRL;
    public static CANJaguar driveDriveRR;
    public static RobotDrive driveMechanumDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANJaguar simpleMotorWinJag;

    public static void init() {
       try { 
            simpleMotorWinJag = new CANJaguar(6);
        } catch (CANTimeoutException ex) {
            System.out.println("FAIL - Instantiating JAG 6");
            ex.printStackTrace();
        }
	
       System.out.println("1st motor done!");
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        try { 
            simpleMotorCimJag = new CANJaguar(5);
        } catch (CANTimeoutException ex) {
            System.out.println("FAIL - Instantiating JAG 5");
            ex.printStackTrace();
        }
	
        
        try { 
            driveDriveFL = new CANJaguar(3);
        } catch (CANTimeoutException ex) {
            System.out.println("FAIL - Instantiating JAG 3");
            ex.printStackTrace();
        }
	
        
        try { 
            driveDriveFR = new CANJaguar(2);
        } catch (CANTimeoutException ex) {
            System.out.println("FAIL - Instantiating JAG 2");
            ex.printStackTrace();
        }
	
        
        try { 
            driveDriveRL = new CANJaguar(7);
        } catch (CANTimeoutException ex) {
            System.out.println("FAIL - Instantiating JAG 7");
            ex.printStackTrace();
        }
	
        
        try { 
            driveDriveRR = new CANJaguar(8);
        } catch (CANTimeoutException ex) {
            System.out.println("FAIL - Instantiating JAG 8");
            ex.printStackTrace();
        }
	
        
        try { 
//        driveMechanumDrive = new RobotDrive(driveDriveFR, driveDriveFL, driveDriveRL, driveDriveRR);
        driveMechanumDrive = new RobotDrive(driveDriveFL, driveDriveFL, driveDriveFL, driveDriveFL);
        }
        catch (Exception e)
        {
            System.out.println("Can't get mech drive going...  FAIL");
        }

        if(driveMechanumDrive == null) System.out.println("MD = NULL");
        
        try {
        driveMechanumDrive.setSafetyEnabled(false);
        driveMechanumDrive.setExpiration(4.0);
        driveMechanumDrive.setSensitivity(0.5);
        driveMechanumDrive.setMaxOutput(1.0);
        }
        catch (Exception e)
        {
            System.out.println("Can't configure mech drive ...  FAIL");
        }
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
